Feat/config file parsing
Jakobus42/webserv pull request #12
Opened 2024-11-20 13:26 UTC by AJMCoding

### Description

Added some config files + a class that is able to parse a configfile data into a struct.

### Type of Change

- [ ] Bug fix
- [x] New feature
- [ ] Documentation update

### How to Test

by modifing the configfile_example (located in the config_files folder) or by calling another config file by writing the file name as an input. (./webserv <file_name>)

### Checklist

- [x] Code follows project style guidelines
- [x] Documentation has been updated

2024-11-21 12:24 UTC, Jakobus42 requested changes
Hey:) Thank you for your first PR.
In general the config parser looks fairly okay but I still found some issues I would be happy to be fixed.

I would suggest to abstract and group common  functionality.
It also would make sense to go over the code again and try to make it simpler / more readable.
What I mean by this is separating bigger functions into smaller ones. 

Also you should try to not use so many "magic values" try to use enums and constants for those cases.

Please name your module "config" instead of config parser. Aswell as the namespace and the class.
Also move your config_files into the config folder with the existing 2 example config files.

2024-11-21 12:24 UTC, Jakobus42 commented on src/configfile/Parser_helpers.cpp
> +          allowed_methods.push_back(args[i]);
I am confused

2024-11-21 12:24 UTC, Jakobus42 commented on src/configfile/Parser_helpers.cpp
> +}
This solution seems like a work around to test pvt member functions. I am sure there is a better way

2024-11-21 12:24 UTC, Jakobus42 commented on include/configfile/Parser.hpp
> +struct location {
why is this not a typedef?

2024-11-21 12:24 UTC, Jakobus42 commented on src/configfile/Parser_helpers.cpp
> +int ft_stoi(std::string str) {
Why not use stringstream instead of writing your own stoi?

2024-11-21 12:24 UTC, Jakobus42 commented on src/configfile/Parser.cpp
> +/* ConfigFileParser::ConfigFileParser(std::string &configFileName)
Please dont submit commented out code.

2024-11-28 21:16 UTC, rwxg commented
I'll be honest, this code makes my head spin. As long as it truly works, reliably and as expected, and it remains a black box that runs exactly once at startup, I'm _fine_ with this staying as-is.

2024-11-29 15:05 UTC, Jakobus42 submitted a review, later dismissed

2024-11-29 15:47 UTC, rwxg approved these changes
LGTM

2024-11-29 15:48 UTC, merged